stages:
  - deploy

deploy_development:
  stage: deploy
  tags:
    - ui_kit
  environment: Development
  only:
    - main
  script:
    - cp -R src/. /var/www/html/test/ui_kit/storybook/vue-ui-kit/src/
    - cp -R public/. /var/www/html/test/ui_kit/storybook/vue-ui-kit/public/
    - cp -R .storybook/. /var/www/html/test/ui_kit/storybook/vue-ui-kit/.storybook/
    - cp package.json /var/www/html/test/ui_kit/storybook/vue-ui-kit/
    - cd /var/www/html/test/ui_kit/storybook/vue-ui-kit
    - npm install
    - npm run build-storybook

# deploy_production:
#   stage: deploy
#   tags:
#     - rena
#   environment: Production
#   only:
#     - production
#   script:
#     - echo $CI_RUNNER_DESCRIPTION
#     # - npm run generate
#     - cp -R dist/. /var/www/html/live/rena_app_v2/
#     - cp -R . /var/www/html/live/demobank/
#     - cd /var/www/html/live/demobank/
#     - npm install
#     - npm run build
#     - cp -R dist/. /var/www/html/live/demobank/
