import convertObjToVars from "../utils/convertObjToVars";
import { generateColorSpectrum } from "../utils/colorManager";

const defaultTheme = {
  "light-primary-action-color": "#0db9e9",
  "light-primary-action-text-color": "#212934",
  "light-text-color": "#212934",
  "light-primary-action-hover-color": "#43d2fa",
  "light-primary-action-text-hover-color": "#ffffff",
  "light-primary-action-disabled-color": "#bdf3fc",
  // light-primary-action-disabled-text-color: "",
  "light-primary-action-box-shadow-color": "rgba(67, 210, 250, 0.25)",
  "light-secondary-action-color": "",
  "light-subtle-text-color": "#ced6de",
  "light-secondary-action-disabled-color": "",
  "light-input-background-color": "#ffffff",
  "light-background-color": "#ffffff",
  "light-outline-action-color": "#0d7fe9",
  "light-outline-action-disabled-color": "#acd7ff",
  "light-outline-action-box-shadow-color": "rgba(27, 92, 224, 0.2)",

  "dark-primary-action-color": "#0db9e9",
  "dark-text-color": "#212934",
  "dark-primary-action-hover-color": "#43d2fa",
  "dark-primary-action-disabled-color": "#bdf3fc",
  "dark-primary-action-box-shadow-color": "rgba(67, 210, 250, 0.25)",
  "dark-secondary-action-color": "",
  "dark-subtle-text-color": "#ced6de",
  "dark-secondary-action-disabled-color": "",
  "dark-input-background-color": "#1F2B3B",
  "dark-input-label-color": "#94A3B8",
  "dark-input-border-color": "#384860",
  "dark-input-icon-color": "#94A3B8",
  "dark-background-color": "#121A26",
  "dark-input-disabled-text-color": "rgba(148, 163, 184, 0.8)",
  "light-primary-100": "#f2fafc",
  "light-primary-200": "#bdf3fc",
  "light-primary-300": "#75e2fa",
  "light-primary-400": "#43d2fa",
  "light-primary-500": "#0db9e9",
  "light-primary-600": "#0c9ccc",
  "light-primary-700": "#0b87b0",
  "light-primary-800": "#085e7a",
  "light-primary-900": "#094357",
  "dark-primary-100": "#56c7ee",
  "dark-primary-200": "#36bdea",
  "dark-primary-300": "#0b87b0",
  "dark-primary-400": "#0c9ccc",
  "dark-primary-500": "#1494bf",
  "dark-primary-600": "#1182a8",
  "dark-primary-700": "#0f6d8d",
  "dark-primary-800": "#085e7a",
  "dark-primary-900": "#094357",
};

export const defaultThemeVars = {
  ...convertObjToVars(defaultTheme),
  ...generateColorSpectrum("#121A26", "--dark-background-"),
};

export default defaultTheme;
